version: '3'

services:
  ui:
    build: .
    ports:
      - "80:80"
    volumes:
      - "./public:/usr/share/nginx/html"
  app:
    build: .
    ports:
      - "82:80"
    volumes:
      - "./public:/usr/share/nginx/html"